FROM node:alpine

# Copy the files from the host file system to the image file system
COPY . /app

# Set the working directory in the image
WORKDIR /app

# Run a command to start the application
CMD node app.js 

